### ISSUE TITLE
Public license removal

### ISSUE THREAD

**Issue by moucek** [INCF/eeg-database#121]
Please remove "Public license" from the list of offered licenses.

**Comment by rinkesj** [comment]
Production server ?

**Comment by rinkesj** [comment]
If u think this Public license on experiments page:
![portal1](https://cloud.githubusercontent.com/assets/1951770/6959765/7d5347de-d91c-11e4-9369-78253696e71f.png)

Public license is in list because someone attached this license to package on manage package page:
![portal2](https://cloud.githubusercontent.com/assets/1951770/6959801/d52fa8c6-d91c-11e4-919d-f5c49a812c36.png)

It's not bug.

**Comment by moucek** [comment]
OK,  thank you, in this case we have to discuss it with experimentalists first.
